Mar 25 21:39:31 cloud-init[1804]: util.py[DEBUG]: Cloud-init v. 0.7.6 running 'init-local' at Wed, 25 Mar 2020 21:39:31 +0000. Up 6.67 seconds.
Mar 25 21:39:31 cloud-init[1804]: util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [644] 0 bytes
Mar 25 21:39:31 cloud-init[1804]: util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance/boot-finished
Mar 25 21:39:31 cloud-init[1804]: util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
Mar 25 21:39:31 cloud-init[1804]: util.py[DEBUG]: Attempting to remove /var/lib/cloud/data/no-net
Mar 25 21:39:31 cloud-init[1804]: util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
Mar 25 21:39:31 cloud-init[1804]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Mar 25 21:39:31 cloud-init[1804]: __init__.py[DEBUG]: Looking for for data source in: ['Ec2', 'None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM']
Mar 25 21:39:31 cloud-init[1804]: __init__.py[DEBUG]: Searching for data source in: []
Mar 25 21:39:31 cloud-init[1804]: cloud-init[DEBUG]: No local datasource found
Mar 25 21:39:31 cloud-init[1804]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
Mar 25 21:39:31 cloud-init[1804]: util.py[DEBUG]: Read 10 bytes from /proc/uptime
Mar 25 21:39:31 cloud-init[1804]: util.py[DEBUG]: cloud-init mode 'init' took 0.042 seconds (0.04)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Cloud-init v. 0.7.6 running 'init' at Wed, 25 Mar 2020 21:39:31 +0000. Up 6.82 seconds.
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [644] 0 bytes
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Running command ['ifconfig', '-a'] with allowed return codes [0] (shell=False, capture=True)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Running command ['netstat', '-rn'] with allowed return codes [0] (shell=False, capture=True)
Mar 25 21:39:31 cloud-init[1815]: cloud-init[DEBUG]: Checking to see if files that we need already exist from a previous run that would allow us to stop early.
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Reading from /var/lib/cloud/data/no-net (quiet=False)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
Mar 25 21:39:31 cloud-init[1815]: cloud-init[DEBUG]: Execution continuing, no previous run detected that would allow us to stop early.
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
Mar 25 21:39:31 cloud-init[1815]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Mar 25 21:39:31 cloud-init[1815]: __init__.py[DEBUG]: Looking for for data source in: ['Ec2', 'None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM', 'NETWORK']
Mar 25 21:39:31 cloud-init[1815]: __init__.py[DEBUG]: Searching for data source in: ['DataSourceEc2', 'DataSourceNone']
Mar 25 21:39:31 cloud-init[1815]: __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceEc2.DataSourceEc2'>
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Reading from /var/lib/cloud/seed/ec2/meta-data (quiet=False)
Mar 25 21:39:31 cloud-init[1815]: DataSourceEc2.py[DEBUG]: Removed the following from metadata urls: ['http://instance-data.:8773']
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254/latest/meta-data/instance-id' with {'url': 'http://169.254.169.254/latest/meta-data/instance-id', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 50.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/instance-id (200, 19b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: DataSourceEc2.py[DEBUG]: Using metadata source: 'http://169.254.169.254'
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/user-data' with {'url': 'http://169.254.169.254/latest/user-data', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/user-data (200, 3160b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/' with {'url': 'http://169.254.169.254/latest/meta-data/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/ (200, 285b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/block-device-mapping/' with {'url': 'http://169.254.169.254/latest/meta-data/block-device-mapping/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/block-device-mapping/ (200, 8b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/block-device-mapping/ami' with {'url': 'http://169.254.169.254/latest/meta-data/block-device-mapping/ami', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/block-device-mapping/ami (200, 4b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/block-device-mapping/root' with {'url': 'http://169.254.169.254/latest/meta-data/block-device-mapping/root', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/block-device-mapping/root (200, 9b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/events/' with {'url': 'http://169.254.169.254/latest/meta-data/events/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/events/ (200, 12b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/events/maintenance/' with {'url': 'http://169.254.169.254/latest/meta-data/events/maintenance/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/events/maintenance/ (200, 17b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/events/maintenance/scheduled' with {'url': 'http://169.254.169.254/latest/meta-data/events/maintenance/scheduled', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/events/maintenance/scheduled (200, 2b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/events/maintenance/history' with {'url': 'http://169.254.169.254/latest/meta-data/events/maintenance/history', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/events/maintenance/history (200, 2b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/iam/' with {'url': 'http://169.254.169.254/latest/meta-data/iam/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/iam/ (200, 26b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/iam/info' with {'url': 'http://169.254.169.254/latest/meta-data/iam/info', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/iam/info (200, 216b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/identity-credentials/' with {'url': 'http://169.254.169.254/latest/meta-data/identity-credentials/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/identity-credentials/ (200, 4b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/identity-credentials/ec2/' with {'url': 'http://169.254.169.254/latest/meta-data/identity-credentials/ec2/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/identity-credentials/ec2/ (200, 26b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/identity-credentials/ec2/info' with {'url': 'http://169.254.169.254/latest/meta-data/identity-credentials/ec2/info', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/identity-credentials/ec2/info (200, 98b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/metrics/' with {'url': 'http://169.254.169.254/latest/meta-data/metrics/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/metrics/ (200, 7b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/metrics/vhostmd' with {'url': 'http://169.254.169.254/latest/meta-data/metrics/vhostmd', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/metrics/vhostmd (200, 38b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/' with {'url': 'http://169.254.169.254/latest/meta-data/network/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/ (200, 11b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/ (200, 5b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/ (200, 18b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/ (200, 230b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/ipv4-associations/' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/ipv4-associations/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/ipv4-associations/ (200, 14b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/ipv4-associations/34.229.180.228' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/ipv4-associations/34.229.180.228', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/ipv4-associations/34.229.180.228 (200, 13b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/local-hostname' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/local-hostname', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/local-hostname (200, 29b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/security-groups' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/security-groups', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/security-groups (200, 56b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/public-hostname' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/public-hostname', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/public-hostname (200, 42b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/vpc-ipv4-cidr-blocks' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/vpc-ipv4-cidr-blocks', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/vpc-ipv4-cidr-blocks (200, 13b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/subnet-id' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/subnet-id', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/subnet-id (200, 15b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/public-ipv4s' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/public-ipv4s', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/public-ipv4s (200, 14b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/interface-id' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/interface-id', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/interface-id (200, 21b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/mac' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/mac', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/mac (200, 17b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/security-group-ids' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/security-group-ids', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/security-group-ids (200, 20b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/vpc-ipv4-cidr-block' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/vpc-ipv4-cidr-block', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/vpc-ipv4-cidr-block (200, 13b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/local-ipv4s' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/local-ipv4s', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/local-ipv4s (200, 13b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/owner-id' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/owner-id', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/owner-id (200, 12b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/subnet-ipv4-cidr-block' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/subnet-ipv4-cidr-block', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/subnet-ipv4-cidr-block (200, 14b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/device-number' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/device-number', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/device-number (200, 1b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/vpc-id' with {'url': 'http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/vpc-id', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/network/interfaces/macs/0e:65:3e:19:03:cd/vpc-id (200, 12b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/placement/' with {'url': 'http://169.254.169.254/latest/meta-data/placement/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/placement/ (200, 17b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/placement/availability-zone' with {'url': 'http://169.254.169.254/latest/meta-data/placement/availability-zone', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/placement/availability-zone (200, 10b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/services/' with {'url': 'http://169.254.169.254/latest/meta-data/services/', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/services/ (200, 16b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/services/domain' with {'url': 'http://169.254.169.254/latest/meta-data/services/domain', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/services/domain (200, 13b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/services/partition' with {'url': 'http://169.254.169.254/latest/meta-data/services/partition', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/services/partition (200, 3b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/profile' with {'url': 'http://169.254.169.254/latest/meta-data/profile', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/profile (200, 11b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/local-ipv4' with {'url': 'http://169.254.169.254/latest/meta-data/local-ipv4', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/local-ipv4 (200, 13b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/reservation-id' with {'url': 'http://169.254.169.254/latest/meta-data/reservation-id', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/reservation-id (200, 19b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/local-hostname' with {'url': 'http://169.254.169.254/latest/meta-data/local-hostname', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/local-hostname (200, 29b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/security-groups' with {'url': 'http://169.254.169.254/latest/meta-data/security-groups', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/security-groups (200, 56b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/ami-launch-index' with {'url': 'http://169.254.169.254/latest/meta-data/ami-launch-index', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/ami-launch-index (200, 1b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/public-hostname' with {'url': 'http://169.254.169.254/latest/meta-data/public-hostname', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/public-hostname (200, 42b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/hostname' with {'url': 'http://169.254.169.254/latest/meta-data/hostname', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/hostname (200, 29b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/ami-id' with {'url': 'http://169.254.169.254/latest/meta-data/ami-id', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/ami-id (200, 21b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/instance-action' with {'url': 'http://169.254.169.254/latest/meta-data/instance-action', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/instance-action (200, 4b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/mac' with {'url': 'http://169.254.169.254/latest/meta-data/mac', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/mac (200, 17b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/public-ipv4' with {'url': 'http://169.254.169.254/latest/meta-data/public-ipv4', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/public-ipv4 (200, 14b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/ami-manifest-path' with {'url': 'http://169.254.169.254/latest/meta-data/ami-manifest-path', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/ami-manifest-path (200, 9b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/instance-type' with {'url': 'http://169.254.169.254/latest/meta-data/instance-type', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/instance-type (200, 7b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/meta-data/instance-id' with {'url': 'http://169.254.169.254/latest/meta-data/instance-id', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/meta-data/instance-id (200, 19b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/dynamic/instance-identity' with {'url': 'http://169.254.169.254/latest/dynamic/instance-identity', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/dynamic/instance-identity (200, 32b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/dynamic/instance-identity/document' with {'url': 'http://169.254.169.254/latest/dynamic/instance-identity/document', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/dynamic/instance-identity/document (200, 476b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/dynamic/instance-identity/signature' with {'url': 'http://169.254.169.254/latest/dynamic/instance-identity/signature', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/dynamic/instance-identity/signature (200, 174b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/dynamic/instance-identity/pkcs7' with {'url': 'http://169.254.169.254/latest/dynamic/instance-identity/pkcs7', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/dynamic/instance-identity/pkcs7 (200, 1114b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254/latest/dynamic/instance-identity/rsa2048' with {'url': 'http://169.254.169.254/latest/dynamic/instance-identity/rsa2048', 'headers': {'User-Agent': 'Cloud-Init/0.7.6'}, 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0} configuration
Mar 25 21:39:31 cloud-init[1815]: url_helper.py[DEBUG]: Read from http://169.254.169.254/latest/dynamic/instance-identity/rsa2048 (200, 1434b) after 1 attempts
Mar 25 21:39:31 cloud-init[1815]: DataSourceEc2.py[DEBUG]: Crawl of metadata service took 0 seconds
Mar 25 21:39:31 cloud-init[1815]: stages.py[INFO]: Loaded datasource DataSourceEc2 - DataSourceEc2
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Reading from /proc/cmdline (quiet=False)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Read 111 bytes from /proc/cmdline
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Read 559 bytes from /etc/cloud/cloud.cfg
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Attempting to load yaml from string of length 559 with allowed root types (<type 'dict'>,)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg (quiet=False)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Read 586 bytes from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Attempting to load yaml from string of length 586 with allowed root types (<type 'dict'>,)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Read 1963 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Attempting to load yaml from string of length 1963 with allowed root types (<type 'dict'>,)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/00_defaults.cfg (quiet=False)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Read 2610 bytes from /etc/cloud/cloud.cfg.d/00_defaults.cfg
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Attempting to load yaml from string of length 2610 with allowed root types (<type 'dict'>,)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/i-086294e0af6373aac'
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Reading from /var/lib/cloud/instances/i-086294e0af6373aac/datasource (quiet=False)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-086294e0af6373aac/datasource - wb: [644] 29 bytes
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 29 bytes
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 20 bytes
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 20 bytes
Mar 25 21:39:31 cloud-init[1815]: cloud-init[DEBUG]: init will now be targeting instance id: i-086294e0af6373aac
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Reading from /proc/cmdline (quiet=False)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Read 111 bytes from /proc/cmdline
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Read 559 bytes from /etc/cloud/cloud.cfg
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Attempting to load yaml from string of length 559 with allowed root types (<type 'dict'>,)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg (quiet=False)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Read 586 bytes from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Attempting to load yaml from string of length 586 with allowed root types (<type 'dict'>,)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Read 1963 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Attempting to load yaml from string of length 1963 with allowed root types (<type 'dict'>,)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/00_defaults.cfg (quiet=False)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Read 2610 bytes from /etc/cloud/cloud.cfg.d/00_defaults.cfg
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Attempting to load yaml from string of length 2610 with allowed root types (<type 'dict'>,)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 11804 bytes
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-086294e0af6373aac/user-data.txt - wb: [600] 3160 bytes
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Attempting to load yaml from string of length 105 with allowed root types (<type 'dict'>,)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-086294e0af6373aac/user-data.txt.i - wb: [600] 3219 bytes
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-086294e0af6373aac/vendor-data.txt - wb: [600] 4 bytes
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-086294e0af6373aac/vendor-data.txt.i - wb: [600] 345 bytes
Mar 25 21:39:31 cloud-init[1815]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-086294e0af6373aac/sem/consume_data - wb: [644] 20 bytes
Mar 25 21:39:31 cloud-init[1815]: helpers.py[DEBUG]: Running consume_data using lock (<FileLock using file '/var/lib/cloud/instances/i-086294e0af6373aac/sem/consume_data'>)
Mar 25 21:39:31 cloud-init[1815]: launch_index.py[DEBUG]: Discarding 0 multipart messages which do not match launch index 0
Mar 25 21:39:31 cloud-init[1815]: stages.py[DEBUG]: Added default handler for set(['text/cloud-config-jsonp', 'text/cloud-config']) from CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']]
Mar 25 21:39:31 cloud-init[1815]: stages.py[DEBUG]: Added default handler for set(['text/x-shellscript']) from ShellScriptPartHandler: [['text/x-shellscript']]
Mar 25 21:39:31 cloud-init[1815]: stages.py[DEBUG]: Added default handler for set(['text/cloud-boothook']) from BootHookPartHandler: [['text/cloud-boothook']]
Mar 25 21:39:31 cloud-init[1815]: stages.py[DEBUG]: Added default handler for set(['text/upstart-job']) from UpstartJobPartHandler: [['text/upstart-job']]
Mar 25 21:39:31 cloud-init[1815]: __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__begin__, None, 2) with frequency once-per-instance
Mar 25 21:39:31 cloud-init[1815]: __init__.py[DEBUG]: Calling handler UpstartJobPartHandler: [['text/upstart-job']] (__begin__, None, 2) with frequency once-per-instance
Mar 25 21:39:31 cloud-init[1815]: __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__begin__, None, 3) with frequency once-per-instance
Mar 25 21:39:31 cloud-init[1815]: __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__begin__, None, 2) with frequency once-per-instance
Mar 25 21:39:31 cloud-init[1815]: __init__.py[DEBUG]: {'Content-Transfer-Encoding': '7bit', 'Content-Type': 'text/cloud-config; charset="us-ascii"', 'Content-Disposition': 'attachment; filename="cloud-config.txt"', 'MIME-Version': '1.0'}
Mar 25 21:39:31 cloud-init[1815]: __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (text/cloud-config, cloud-config.txt, 3) with frequency once-per-instance
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Attempting to load yaml from string of length 105 with allowed root types (<type 'dict'>,)
Mar 25 21:39:31 cloud-init[1815]: cloud_config.py[DEBUG]: Merging by applying [('dict', ['replace']), ('list', []), ('str', [])]
Mar 25 21:39:31 cloud-init[1815]: __init__.py[DEBUG]: {'Content-Transfer-Encoding': '7bit', 'Content-Type': 'text/x-shellscript; charset="us-ascii"', 'Content-Disposition': 'attachment; filename="user-data.txt"', 'MIME-Version': '1.0'}
Mar 25 21:39:31 cloud-init[1815]: __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (text/x-shellscript, user-data.txt, 2) with frequency once-per-instance
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Writing to /var/lib/cloud/instance/scripts/user-data.txt - wb: [700] 2510 bytes
Mar 25 21:39:31 cloud-init[1815]: __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__end__, None, 2) with frequency once-per-instance
Mar 25 21:39:31 cloud-init[1815]: __init__.py[DEBUG]: Calling handler UpstartJobPartHandler: [['text/upstart-job']] (__end__, None, 2) with frequency once-per-instance
Mar 25 21:39:31 cloud-init[1815]: __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__end__, None, 3) with frequency once-per-instance
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-086294e0af6373aac/cloud-config.txt - wb: [600] 155 bytes
Mar 25 21:39:31 cloud-init[1815]: __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__end__, None, 2) with frequency once-per-instance
Mar 25 21:39:31 cloud-init[1815]: stages.py[DEBUG]: no vendordata from datasource
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Reading from /proc/cmdline (quiet=False)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Read 111 bytes from /proc/cmdline
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Read 559 bytes from /etc/cloud/cloud.cfg
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Attempting to load yaml from string of length 559 with allowed root types (<type 'dict'>,)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg (quiet=False)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Read 586 bytes from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Attempting to load yaml from string of length 586 with allowed root types (<type 'dict'>,)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Read 1963 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Attempting to load yaml from string of length 1963 with allowed root types (<type 'dict'>,)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/00_defaults.cfg (quiet=False)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Read 2610 bytes from /etc/cloud/cloud.cfg.d/00_defaults.cfg
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Attempting to load yaml from string of length 2610 with allowed root types (<type 'dict'>,)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Read 155 bytes from /var/lib/cloud/instance/cloud-config.txt
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Attempting to load yaml from string of length 155 with allowed root types (<type 'dict'>,)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Read 155 bytes from /var/lib/cloud/instance/cloud-config.txt
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Attempting to load yaml from string of length 155 with allowed root types (<type 'dict'>,)
Mar 25 21:39:31 cloud-init[1815]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Mar 25 21:39:31 cloud-init[1815]: stages.py[INFO]: Skipping modules ['resolv-conf'] because they are not verified on distro 'amazon'.  To run anyway, add them to 'unverified_modules' in config.
Mar 25 21:39:31 cloud-init[1815]: stages.py[DEBUG]: Running module migrator (<module 'cloudinit.config.cc_migrator' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_migrator.pyc'>) with frequency always
Mar 25 21:39:31 cloud-init[1815]: helpers.py[DEBUG]: Running config-migrator using lock (<cloudinit.helpers.DummyLock object at 0x7f1a463bf850>)
Mar 25 21:39:31 cloud-init[1815]: cc_migrator.py[DEBUG]: Migrating semaphores which are not named canonically.
Mar 25 21:39:31 cloud-init[1815]: cc_migrator.py[DEBUG]: Looking at consume_data
Mar 25 21:39:31 cloud-init[1815]: cc_migrator.py[DEBUG]: Searching for legacy per-instance semaphores under /var/lib/cloud/sem
Mar 25 21:39:31 cloud-init[1815]: cc_migrator.py[DEBUG]: Migrating semaphores which have been renamed or split.
Mar 25 21:39:31 cloud-init[1815]: cc_migrator.py[DEBUG]: Looking in /var/lib/cloud/instances/i-086294e0af6373aac/sem
Mar 25 21:39:31 cloud-init[1815]: cc_migrator.py[DEBUG]: Looking in /var/lib/cloud/sem
Mar 25 21:39:31 cloud-init[1815]: stages.py[DEBUG]: Running module rsyslog (<module 'cloudinit.config.cc_rsyslog' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_rsyslog.pyc'>) with frequency once-per-instance
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-086294e0af6373aac/sem/config_rsyslog - wb: [644] 19 bytes
Mar 25 21:39:31 cloud-init[1815]: helpers.py[DEBUG]: Running config-rsyslog using lock (<FileLock using file '/var/lib/cloud/instances/i-086294e0af6373aac/sem/config_rsyslog'>)
Mar 25 21:39:31 cloud-init[1815]: cc_rsyslog.py[DEBUG]: Skipping module named rsyslog, no 'rsyslog' key in configuration
Mar 25 21:39:31 cloud-init[1815]: stages.py[DEBUG]: Running module bootcmd (<module 'cloudinit.config.cc_bootcmd' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_bootcmd.pyc'>) with frequency always
Mar 25 21:39:31 cloud-init[1815]: helpers.py[DEBUG]: Running config-bootcmd using lock (<cloudinit.helpers.DummyLock object at 0x7f1a466a9e50>)
Mar 25 21:39:31 cloud-init[1815]: cc_bootcmd.py[DEBUG]: Skipping module named bootcmd, no 'bootcmd' key in configuration
Mar 25 21:39:31 cloud-init[1815]: stages.py[DEBUG]: Running module write-files (<module 'cloudinit.config.cc_write_files' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_write_files.pyc'>) with frequency once-per-instance
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-086294e0af6373aac/sem/config_write_files - wb: [644] 19 bytes
Mar 25 21:39:31 cloud-init[1815]: helpers.py[DEBUG]: Running config-write-files using lock (<FileLock using file '/var/lib/cloud/instances/i-086294e0af6373aac/sem/config_write_files'>)
Mar 25 21:39:31 cloud-init[1815]: cc_write_files.py[DEBUG]: Skipping module named write-files, no/empty 'write_files' key in configuration
Mar 25 21:39:31 cloud-init[1815]: stages.py[DEBUG]: Running module write-metadata (<module 'cloudinit.config.cc_write_metadata' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_write_metadata.pyc'>) with frequency once-per-instance
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-086294e0af6373aac/sem/config_write_metadata - wb: [644] 20 bytes
Mar 25 21:39:31 cloud-init[1815]: helpers.py[DEBUG]: Running config-write-metadata using lock (<FileLock using file '/var/lib/cloud/instances/i-086294e0af6373aac/sem/config_write_metadata'>)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Writing to /etc/yum/vars/awsregion - wb: [644] 9 bytes
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Changing the ownership of /etc/yum/vars/awsregion to 0:0
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Writing to /etc/yum/vars/awsdomain - wb: [644] 13 bytes
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Changing the ownership of /etc/yum/vars/awsdomain to 0:0
Mar 25 21:39:31 cloud-init[1815]: stages.py[DEBUG]: Running module growpart (<module 'cloudinit.config.cc_growpart' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_growpart.pyc'>) with frequency always
Mar 25 21:39:31 cloud-init[1815]: helpers.py[DEBUG]: Running config-growpart using lock (<cloudinit.helpers.DummyLock object at 0x7f1a466a9e50>)
Mar 25 21:39:31 cloud-init[1815]: cc_growpart.py[DEBUG]: No 'growpart' entry in cfg.  Using default: {'ignore_growroot_disabled': False, 'mode': 'auto', 'devices': ['/']}
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Running command ['growpart', '--help'] with allowed return codes [0] (shell=False, capture=True)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Reading from /proc/1815/mountinfo (quiet=False)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Read 531 bytes from /proc/1815/mountinfo
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Reading from /sys/class/block/nvme0n1p1/partition (quiet=False)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Read 2 bytes from /sys/class/block/nvme0n1p1/partition
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Reading from /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1/dev (quiet=False)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Read 6 bytes from /sys/devices/pci0000:00/0000:00:04.0/nvme/nvme0/nvme0n1/dev
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Running command ['growpart', '--dry-run', '/dev/nvme0n1', '1'] with allowed return codes [0] (shell=False, capture=True)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: resize_devices took 0.030 seconds
Mar 25 21:39:31 cloud-init[1815]: cc_growpart.py[DEBUG]: '/' NOCHANGE: no change necessary (/dev/nvme0n1, 1)
Mar 25 21:39:31 cloud-init[1815]: stages.py[DEBUG]: Running module resizefs (<module 'cloudinit.config.cc_resizefs' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_resizefs.pyc'>) with frequency always
Mar 25 21:39:31 cloud-init[1815]: helpers.py[DEBUG]: Running config-resizefs using lock (<cloudinit.helpers.DummyLock object at 0x7f1a466a90d0>)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Reading from /proc/1815/mountinfo (quiet=False)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Read 531 bytes from /proc/1815/mountinfo
Mar 25 21:39:31 cloud-init[1815]: cc_resizefs.py[DEBUG]: resize_info: dev=/dev/nvme0n1p1 mnt_point=/ path=/
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Read 53 bytes from /proc/1/environ
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Read 1298 bytes from /proc/self/status
Mar 25 21:39:31 cloud-init[1815]: cc_resizefs.py[DEBUG]: Resizing / (ext4) using resize2fs /dev/nvme0n1p1
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Forked child 1847 who will run callback log_time
Mar 25 21:39:31 cloud-init[1815]: cc_resizefs.py[DEBUG]: Resizing (via forking) root filesystem (type=ext4, val=noblock)
Mar 25 21:39:31 cloud-init[1815]: stages.py[DEBUG]: Running module set-hostname (<module 'cloudinit.config.cc_set_hostname' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_set_hostname.pyc'>) with frequency once-per-instance
Mar 25 21:39:31 cloud-init[1847]: util.py[DEBUG]: Running command ('resize2fs', '/dev/nvme0n1p1') with allowed return codes [0] (shell=False, capture=True)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-086294e0af6373aac/sem/config_set_hostname - wb: [644] 20 bytes
Mar 25 21:39:31 cloud-init[1815]: helpers.py[DEBUG]: Running config-set-hostname using lock (<FileLock using file '/var/lib/cloud/instances/i-086294e0af6373aac/sem/config_set_hostname'>)
Mar 25 21:39:31 cloud-init[1815]: cc_set_hostname.py[DEBUG]: Configuration option 'preserve_hostname' is set, not setting the hostname in module set-hostname
Mar 25 21:39:31 cloud-init[1815]: stages.py[DEBUG]: Running module update-hostname (<module 'cloudinit.config.cc_update_hostname' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_update_hostname.pyc'>) with frequency always
Mar 25 21:39:31 cloud-init[1815]: helpers.py[DEBUG]: Running config-update-hostname using lock (<cloudinit.helpers.DummyLock object at 0x7f1a4632e710>)
Mar 25 21:39:31 cloud-init[1815]: cc_update_hostname.py[DEBUG]: Configuration option 'preserve_hostname' is set, not updating the hostname in module update-hostname
Mar 25 21:39:31 cloud-init[1815]: stages.py[DEBUG]: Running module update-etc-hosts (<module 'cloudinit.config.cc_update_etc_hosts' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_update_etc_hosts.pyc'>) with frequency always
Mar 25 21:39:31 cloud-init[1815]: helpers.py[DEBUG]: Running config-update-etc-hosts using lock (<cloudinit.helpers.DummyLock object at 0x7f1a4632e650>)
Mar 25 21:39:31 cloud-init[1815]: cc_update_etc_hosts.py[DEBUG]: Configuration option 'manage_etc_hosts' is not set, not managing /etc/hosts in module update-etc-hosts
Mar 25 21:39:31 cloud-init[1815]: stages.py[DEBUG]: Running module resolv-conf (<module 'cloudinit.config.cc_resolv_conf' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_resolv_conf.pyc'>) with frequency once-per-instance
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-086294e0af6373aac/sem/config_resolv_conf - wb: [644] 20 bytes
Mar 25 21:39:31 cloud-init[1815]: helpers.py[DEBUG]: Running config-resolv-conf using lock (<FileLock using file '/var/lib/cloud/instances/i-086294e0af6373aac/sem/config_resolv_conf'>)
Mar 25 21:39:31 cloud-init[1815]: cc_resolv_conf.py[DEBUG]: Skipping module named resolv-conf, no 'manage_resolv_conf' key in configuration
Mar 25 21:39:31 cloud-init[1815]: stages.py[DEBUG]: Running module users-groups (<module 'cloudinit.config.cc_users_groups' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_users_groups.pyc'>) with frequency once-per-instance
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-086294e0af6373aac/sem/config_users_groups - wb: [644] 20 bytes
Mar 25 21:39:31 cloud-init[1815]: helpers.py[DEBUG]: Running config-users-groups using lock (<FileLock using file '/var/lib/cloud/instances/i-086294e0af6373aac/sem/config_users_groups'>)
Mar 25 21:39:31 cloud-init[1815]: __init__.py[INFO]: User ec2-user already exists, skipping.
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Running command ['usermod', '-L', 'ec2-user'] with allowed return codes [0] (shell=False, capture=True)
Mar 25 21:39:31 cloud-init[1847]: util.py[DEBUG]: backgrounded Resizing took 0.007 seconds
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Reading from /etc/sudoers (quiet=False)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Read 3729 bytes from /etc/sudoers
Mar 25 21:39:31 cloud-init[1815]: stages.py[DEBUG]: Running module ssh (<module 'cloudinit.config.cc_ssh' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_ssh.pyc'>) with frequency once-per-instance
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-086294e0af6373aac/sem/config_ssh - wb: [644] 20 bytes
Mar 25 21:39:31 cloud-init[1815]: helpers.py[DEBUG]: Running config-ssh using lock (<FileLock using file '/var/lib/cloud/instances/i-086294e0af6373aac/sem/config_ssh'>)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Running command ['ssh-keygen', '-t', 'rsa', '-N', '', '-f', '/etc/ssh/ssh_host_rsa_key'] with allowed return codes [0] (shell=False, capture=False)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Running command ['ssh-keygen', '-t', 'dsa', '-N', '', '-f', '/etc/ssh/ssh_host_dsa_key'] with allowed return codes [0] (shell=False, capture=False)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ecdsa', '-N', '', '-f', '/etc/ssh/ssh_host_ecdsa_key'] with allowed return codes [0] (shell=False, capture=False)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Changing the ownership of /home/ec2-user/.ssh to 500:500
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Read 3935 bytes from /etc/ssh/sshd_config
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Writing to /home/ec2-user/.ssh/authorized_keys - wb: [600] 0 bytes
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Changing the ownership of /home/ec2-user/.ssh/authorized_keys to 500:500
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Read 3935 bytes from /etc/ssh/sshd_config
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Reading from /root/.ssh/authorized_keys (quiet=False)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Read 565 bytes from /root/.ssh/authorized_keys
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 565 bytes
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Changing the ownership of /root/.ssh/authorized_keys to 0:0
Mar 25 21:39:31 cloud-init[1815]: cloud-init[DEBUG]: Ran 13 modules with 0 failures
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: Read 10 bytes from /proc/uptime
Mar 25 21:39:31 cloud-init[1815]: util.py[DEBUG]: cloud-init mode 'init' took 0.600 seconds (0.60)
Mar 25 21:39:32 cloud-init[1866]: util.py[DEBUG]: Cloud-init v. 0.7.6 running 'modules:config' at Wed, 25 Mar 2020 21:39:32 +0000. Up 7.53 seconds.
Mar 25 21:39:32 cloud-init[1866]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Mar 25 21:39:32 cloud-init[1866]: stages.py[DEBUG]: Running module mounts (<module 'cloudinit.config.cc_mounts' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_mounts.pyc'>) with frequency once-per-instance
Mar 25 21:39:32 cloud-init[1866]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-086294e0af6373aac/sem/config_mounts - wb: [644] 20 bytes
Mar 25 21:39:32 cloud-init[1866]: helpers.py[DEBUG]: Running config-mounts using lock (<FileLock using file '/var/lib/cloud/instances/i-086294e0af6373aac/sem/config_mounts'>)
Mar 25 21:39:32 cloud-init[1866]: cc_mounts.py[DEBUG]: Attempting to determine the real name of ephemeral0
Mar 25 21:39:32 cloud-init[1866]: DataSourceEc2.py[DEBUG]: Unable to convert ephemeral0 to a device
Mar 25 21:39:32 cloud-init[1866]: cc_mounts.py[DEBUG]: Ignoring nonexistent named mount ephemeral0
Mar 25 21:39:32 cloud-init[1866]: cc_mounts.py[DEBUG]: changed ephemeral0 => None
Mar 25 21:39:32 cloud-init[1866]: cc_mounts.py[DEBUG]: Attempting to determine the real name of swap
Mar 25 21:39:32 cloud-init[1866]: DataSourceEc2.py[DEBUG]: Unable to convert swap to a device
Mar 25 21:39:32 cloud-init[1866]: cc_mounts.py[DEBUG]: Ignoring nonexistent named mount swap
Mar 25 21:39:32 cloud-init[1866]: cc_mounts.py[DEBUG]: changed swap => None
Mar 25 21:39:32 cloud-init[1866]: cc_mounts.py[DEBUG]: Attempting to determine the real name of ephemeral0
Mar 25 21:39:32 cloud-init[1866]: DataSourceEc2.py[DEBUG]: Unable to convert ephemeral0 to a device
Mar 25 21:39:32 cloud-init[1866]: cc_mounts.py[DEBUG]: Ignoring nonexistant default named mount ephemeral0
Mar 25 21:39:32 cloud-init[1866]: cc_mounts.py[DEBUG]: Attempting to determine the real name of swap
Mar 25 21:39:32 cloud-init[1866]: DataSourceEc2.py[DEBUG]: Unable to convert swap to a device
Mar 25 21:39:32 cloud-init[1866]: cc_mounts.py[DEBUG]: Ignoring nonexistant default named mount swap
Mar 25 21:39:32 cloud-init[1866]: cc_mounts.py[DEBUG]: Skipping non-existent device named None
Mar 25 21:39:32 cloud-init[1866]: cc_mounts.py[DEBUG]: Skipping non-existent device named None
Mar 25 21:39:32 cloud-init[1866]: cc_mounts.py[DEBUG]: no need to setup swap
Mar 25 21:39:32 cloud-init[1866]: cc_mounts.py[DEBUG]: No modifications to fstab needed.
Mar 25 21:39:32 cloud-init[1866]: stages.py[DEBUG]: Running module locale (<module 'cloudinit.config.cc_locale' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_locale.pyc'>) with frequency once-per-instance
Mar 25 21:39:32 cloud-init[1866]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-086294e0af6373aac/sem/config_locale - wb: [644] 20 bytes
Mar 25 21:39:32 cloud-init[1866]: helpers.py[DEBUG]: Running config-locale using lock (<FileLock using file '/var/lib/cloud/instances/i-086294e0af6373aac/sem/config_locale'>)
Mar 25 21:39:32 cloud-init[1866]: cc_locale.py[DEBUG]: Setting locale to en_US.UTF-8
Mar 25 21:39:32 cloud-init[1866]: util.py[DEBUG]: Reading from /etc/sysconfig/i18n (quiet=False)
Mar 25 21:39:32 cloud-init[1866]: util.py[DEBUG]: Read 17 bytes from /etc/sysconfig/i18n
Mar 25 21:39:32 cloud-init[1866]: util.py[DEBUG]: Writing to /etc/sysconfig/i18n - wb: [644] 17 bytes
Mar 25 21:39:32 cloud-init[1866]: stages.py[DEBUG]: Running module set-passwords (<module 'cloudinit.config.cc_set_passwords' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_set_passwords.pyc'>) with frequency once-per-instance
Mar 25 21:39:32 cloud-init[1866]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-086294e0af6373aac/sem/config_set_passwords - wb: [644] 20 bytes
Mar 25 21:39:32 cloud-init[1866]: helpers.py[DEBUG]: Running config-set-passwords using lock (<FileLock using file '/var/lib/cloud/instances/i-086294e0af6373aac/sem/config_set_passwords'>)
Mar 25 21:39:32 cloud-init[1866]: util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
Mar 25 21:39:32 cloud-init[1866]: util.py[DEBUG]: Read 3935 bytes from /etc/ssh/sshd_config
Mar 25 21:39:32 cloud-init[1866]: cc_set_passwords.py[DEBUG]: Replacing auth line 65 with no
Mar 25 21:39:32 cloud-init[1866]: util.py[DEBUG]: Writing to /etc/ssh/sshd_config - wb: [644] 3935 bytes
Mar 25 21:39:32 cloud-init[1866]: util.py[DEBUG]: Running command ['service', 'sshd', 'status'] with allowed return codes [0] (shell=False, capture=True)
Mar 25 21:39:32 cloud-init[1866]: stages.py[DEBUG]: Running module yum-configure (<module 'cloudinit.config.cc_yum_configure' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_yum_configure.pyc'>) with frequency once-per-instance
Mar 25 21:39:32 cloud-init[1866]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-086294e0af6373aac/sem/config_yum_configure - wb: [644] 20 bytes
Mar 25 21:39:32 cloud-init[1866]: helpers.py[DEBUG]: Running config-yum-configure using lock (<FileLock using file '/var/lib/cloud/instances/i-086294e0af6373aac/sem/config_yum_configure'>)
Mar 25 21:39:32 cloud-init[1866]: cc_yum_configure.py[DEBUG]: Generating default repo files
Mar 25 21:39:32 cloud-init[1866]: __init__.py[DEBUG]: filtered distro mirror info: {'regional': u'repo.us-east-1.amazonaws.com'}
Mar 25 21:39:32 cloud-init[1866]: cc_yum_configure.py[DEBUG]: Using mirror: repo.us-east-1.amazonaws.com
Mar 25 21:39:32 cloud-init[1866]: cc_yum_configure.py[INFO]: Setting yum releasever to 2018.03
Mar 25 21:39:32 cloud-init[1866]: util.py[DEBUG]: Writing to /etc/yum.conf - wb: [644] 1065 bytes
Mar 25 21:39:32 cloud-init[1866]: stages.py[DEBUG]: Running module yum-add-repo (<module 'cloudinit.config.cc_yum_add_repo' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_yum_add_repo.pyc'>) with frequency once-per-instance
Mar 25 21:39:32 cloud-init[1866]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-086294e0af6373aac/sem/config_yum_add_repo - wb: [644] 20 bytes
Mar 25 21:39:32 cloud-init[1866]: helpers.py[DEBUG]: Running config-yum-add-repo using lock (<FileLock using file '/var/lib/cloud/instances/i-086294e0af6373aac/sem/config_yum_add_repo'>)
Mar 25 21:39:32 cloud-init[1866]: cc_yum_add_repo.py[DEBUG]: Skipping module named yum-add-repo, no 'yum_repos' configuration found
Mar 25 21:39:32 cloud-init[1866]: stages.py[DEBUG]: Running module package-update-upgrade-install (<module 'cloudinit.config.cc_package_update_upgrade_install' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_package_update_upgrade_install.pyc'>) with frequency once-per-instance
Mar 25 21:39:32 cloud-init[1866]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-086294e0af6373aac/sem/config_package_update_upgrade_install - wb: [644] 20 bytes
Mar 25 21:39:32 cloud-init[1866]: helpers.py[DEBUG]: Running config-package-update-upgrade-install using lock (<FileLock using file '/var/lib/cloud/instances/i-086294e0af6373aac/sem/config_package_update_upgrade_install'>)
Mar 25 21:39:32 cloud-init[1866]: stages.py[DEBUG]: Running module timezone (<module 'cloudinit.config.cc_timezone' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_timezone.pyc'>) with frequency once-per-instance
Mar 25 21:39:32 cloud-init[1866]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-086294e0af6373aac/sem/config_timezone - wb: [644] 20 bytes
Mar 25 21:39:32 cloud-init[1866]: helpers.py[DEBUG]: Running config-timezone using lock (<FileLock using file '/var/lib/cloud/instances/i-086294e0af6373aac/sem/config_timezone'>)
Mar 25 21:39:32 cloud-init[1866]: cc_timezone.py[DEBUG]: Skipping module named timezone, no 'timezone' specified
Mar 25 21:39:32 cloud-init[1866]: stages.py[DEBUG]: Running module puppet (<module 'cloudinit.config.cc_puppet' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_puppet.pyc'>) with frequency once-per-instance
Mar 25 21:39:32 cloud-init[1866]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-086294e0af6373aac/sem/config_puppet - wb: [644] 20 bytes
Mar 25 21:39:32 cloud-init[1866]: helpers.py[DEBUG]: Running config-puppet using lock (<FileLock using file '/var/lib/cloud/instances/i-086294e0af6373aac/sem/config_puppet'>)
Mar 25 21:39:32 cloud-init[1866]: cc_puppet.py[DEBUG]: Skipping module named puppet, no 'puppet' configuration found
Mar 25 21:39:32 cloud-init[1866]: stages.py[DEBUG]: Running module disable-ec2-metadata (<module 'cloudinit.config.cc_disable_ec2_metadata' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_disable_ec2_metadata.pyc'>) with frequency always
Mar 25 21:39:32 cloud-init[1866]: helpers.py[DEBUG]: Running config-disable-ec2-metadata using lock (<cloudinit.helpers.DummyLock object at 0x7fb202bbc310>)
Mar 25 21:39:32 cloud-init[1866]: cc_disable_ec2_metadata.py[DEBUG]: Skipping module named disable-ec2-metadata, disabling the ec2 route not enabled
Mar 25 21:39:32 cloud-init[1866]: stages.py[DEBUG]: Running module runcmd (<module 'cloudinit.config.cc_runcmd' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_runcmd.pyc'>) with frequency once-per-instance
Mar 25 21:39:32 cloud-init[1866]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-086294e0af6373aac/sem/config_runcmd - wb: [644] 20 bytes
Mar 25 21:39:32 cloud-init[1866]: helpers.py[DEBUG]: Running config-runcmd using lock (<FileLock using file '/var/lib/cloud/instances/i-086294e0af6373aac/sem/config_runcmd'>)
Mar 25 21:39:32 cloud-init[1866]: cc_runcmd.py[DEBUG]: Skipping module named runcmd, no 'runcmd' key in configuration
Mar 25 21:39:32 cloud-init[1866]: cloud-init[DEBUG]: Ran 10 modules with 0 failures
Mar 25 21:39:32 cloud-init[1866]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
Mar 25 21:39:32 cloud-init[1866]: util.py[DEBUG]: Read 10 bytes from /proc/uptime
Mar 25 21:39:32 cloud-init[1866]: util.py[DEBUG]: cloud-init mode 'modules' took 0.145 seconds (0.15)
Mar 25 21:39:33 cloud-init[2009]: util.py[DEBUG]: Cloud-init v. 0.7.6 running 'modules:final' at Wed, 25 Mar 2020 21:39:33 +0000. Up 9.17 seconds.
Mar 25 21:39:33 cloud-init[2009]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
Mar 25 21:39:33 cloud-init[2009]: stages.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_scripts_user.pyc'>) with frequency always
Mar 25 21:39:33 cloud-init[2009]: helpers.py[DEBUG]: Running config-scripts-user using lock (<cloudinit.helpers.DummyLock object at 0x7f15cb0a8710>)
Mar 25 21:39:33 cloud-init[2009]: util.py[DEBUG]: Running command ['/var/lib/cloud/instance/scripts/user-data.txt'] with allowed return codes [0] (shell=True, capture=False)
Mar 25 21:39:41 cloud-init[2009]: cloud-init[DEBUG]: Ran 1 modules with 0 failures
Mar 25 21:39:41 cloud-init[2009]: util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/result.json' => '../../var/lib/cloud/data/result.json'
Mar 25 21:39:41 cloud-init[2009]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
Mar 25 21:39:41 cloud-init[2009]: util.py[DEBUG]: Read 12 bytes from /proc/uptime
Mar 25 21:39:41 cloud-init[2009]: util.py[DEBUG]: cloud-init mode 'modules' took 7.794 seconds (7.79)
